name: sliver-maestro
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - pandas==1.1.3
  - numpy==1.19.1
  - matplotlib==3.3.1
  - pip==20.2.3
  - pip:
    - opencv-python==4.4.0.44
    - Pillow==7.2.0
    - scikit-learn==0.23.2
    - scikit-image==0.17.2
    - torch==1.3.1
    - torchvision==0.4.2
    - svg.path==4.0.2
    - pygame==1.9.6
    - ndjson==0.3.1
    - google-cloud-storage==1.31.2
    - notebook==6.1.4
    - gsutil==4.53
